import { ProjectInterface } from "@/dummydata/data";

export const sampleProjects: ProjectInterface[] = [
    {
        name: "Quezon City Office Tower",
        client: "UrbanLife Dev. Corp.",
        location: "Quezon City, Philippines",
        status: "completed",
        description: "Construction of a 20-story commercial office building",
        progress: 100,
        dueDate: "Aug 15, 2024",
        members: 10,
        sensors: 4,
        budget: 35_000_000,
        esgScore: 98,
        certifications: ["Cert #1", "Cert #2", "Cert #3"],
        roiEstimate: 8.5,
        lastAuditDate: "Sep 01, 2024",
    },
    {
        name: "Manila North Bridge Rehabilitation",
        client: "Metro Infra Solutions",
        location: "Manila, Philippines",
        status: "archived",
        description: "Structural strengthening and widening of existing city bridge",
        progress: 100,
        dueDate: "Nov 30, 2023",
        members: 18,
        sensors: 10,
        budget: 85_000_000,
        esgScore: 82,
        certifications: ["Cert #1", "Cert #2", "Cert #3", "Cert #4"],
        roiEstimate: 7.2,
        lastAuditDate: "Dec 15, 2023",
    },
    {
        name: "Davao International Airport Terminal",
        client: "SkyBuild Infra",
        location: "Davao City, Philippines",
        status: "archived",
        description: "Construction of a new passenger terminal and runway extension",
        progress: 100,
        dueDate: "Jul 05, 2022",
        members: 40,
        sensors: 15,
        budget: 220_000_000,
        esgScore: 77,
        certifications: ["Cert #1", "Cert #2", "Cert #3", "Cert #4", "Cert #5"],
        roiEstimate: 9.8,
        lastAuditDate: "Aug 10, 2022",
    },
    {
        name: "Iloilo Container Port Expansion",
        client: "Seagate InfraTech",
        location: "Iloilo, Philippines",
        status: "active",
        description: "Expansion of port facilities including new cargo warehouses and docks",
        progress: 55,
        dueDate: "May 18, 2026",
        members: 22,
        sensors: 14,
        budget: 160_000_000,
        esgScore: 89,
        certifications: ["Cert #1", "Cert #2", "Cert #3"],
        roiEstimate: 11.4,
        lastAuditDate: "Jul 02, 2025",
    },
    {
        name: "Batangas Coastal Highway",
        client: "GreenEnergy Corp.",
        location: "Batangas, Philippines",
        status: "active",
        description: "Construction of a new four-lane coastal highway with bridges",
        progress: 35,
        dueDate: "Apr 12, 2026",
        members: 28,
        sensors: 20,
        budget: 250_000_000,
        esgScore: 93,
        certifications: ["Cert #1", "Cert #2", "Cert #3", "Cert #4"],
        roiEstimate: 13.7,
        lastAuditDate: "Jun 20, 2025",
    },
    {
        name: "Subic Industrial Park Development",
        client: "EcoDev Philippines",
        location: "Subic Bay, Philippines",
        status: "active",
        description: "Construction of industrial park with warehouses and access roads",
        progress: 20,
        dueDate: "Sep 30, 2026",
        members: 35,
        sensors: 22,
        budget: 300_000_000,
        esgScore: 81,
        certifications: ["Cert #1", "Cert #2", "Cert #3", "Cert #4", "Cert #5"],
        roiEstimate: 10.9,
        lastAuditDate: "Jul 15, 2025",
    },
    {
        name: "Pasig River Riverside Walkway",
        client: "BlueWaters Initiative",
        location: "Pasig River, Philippines",
        status: "completed",
        description: "Construction of riverside walkway, retaining walls, and drainage",
        progress: 100,
        dueDate: "Oct 11, 2024",
        members: 16,
        sensors: 9,
        budget: 95_000_000,
        esgScore: 96,
        certifications: ["Cert #1", "Cert #2", "Cert #3"],
        roiEstimate: 6.8,
        lastAuditDate: "Oct 30, 2024",
    },
    {
        name: "Clark Freeport Commercial Complex",
        client: "Luzon InfraWorks",
        location: "Clark, Pampanga, Philippines",
        status: "completed",
        description: "Development of new commercial buildings and access roads",
        progress: 100,
        dueDate: "Feb 20, 2025",
        members: 27,
        sensors: 11,
        budget: 180_000_000,
        esgScore: 78,
        certifications: ["Cert #1", "Cert #2", "Cert #3", "Cert #4"],
        roiEstimate: 9.1,
        lastAuditDate: "Mar 15, 2025",
    },
    {
        name: "Mindoro Agro-Processing Facility",
        client: "AgriTech Developments",
        location: "Mindoro, Philippines",
        status: "completed",
        description: "Construction of agro-industrial plant and storage facilities",
        progress: 100,
        dueDate: "Sep 07, 2024",
        members: 19,
        sensors: 7,
        budget: 75_000_000,
        esgScore: 91,
        certifications: ["Cert #1", "Cert #2", "Cert #3", "Cert #4", "Cert #5"],
        roiEstimate: 10.3,
        lastAuditDate: "Sep 22, 2024",
    },
    {
        name: "Laguna Flood Control Dike",
        client: "SafeWater Infra",
        location: "Laguna, Philippines",
        status: "archived",
        description: "Construction and rehabilitation of flood control dike system",
        progress: 100,
        dueDate: "Dec 10, 2022",
        members: 21,
        sensors: 13,
        budget: 130_000_000,
        esgScore: 74,
        certifications: ["Cert #1", "Cert #2", "Cert #3"],
        roiEstimate: 7.5,
        lastAuditDate: "Dec 29, 2022",
    },
    {
        name: "Zamboanga Polytechnic Campus",
        client: "SmartEdu Builders",
        location: "Zamboanga, Philippines",
        status: "archived",
        description: "Construction of campus buildings and training facilities",
        progress: 100,
        dueDate: "Jun 05, 2023",
        members: 12,
        sensors: 6,
        budget: 110_000_000,
        esgScore: 87,
        certifications: ["Cert #1", "Cert #2", "Cert #3", "Cert #4"],
        roiEstimate: 9.2,
        lastAuditDate: "Jul 01, 2023",
    },
    {
        name: "Palawan Coastal Protection Project",
        client: "EcoMarine Alliance",
        location: "Palawan, Philippines",
        status: "active",
        description: "Construction of seawalls, boardwalks, and coastal defenses",
        progress: 45,
        dueDate: "Aug 25, 2026",
        members: 14,
        sensors: 10,
        budget: 140_000_000,
        esgScore: 97,
        certifications: ["Cert #1", "Cert #2", "Cert #3", "Cert #4", "Cert #5"],
        roiEstimate: 12.1,
        lastAuditDate: "Jul 08, 2025",
    },
    {
        name: "Bulacan Water Treatment Plant",
        client: "ClearWater Infra",
        location: "Bulacan, Philippines",
        status: "active",
        description: "Construction of a modern water treatment and pumping facility",
        progress: 70,
        dueDate: "Nov 19, 2025",
        members: 17,
        sensors: 9,
        budget: 125_000_000,
        esgScore: 84,
        certifications: ["Cert #1", "Cert #2", "Cert #3"],
        roiEstimate: 11.6,
        lastAuditDate: "Jun 30, 2025",
    },
    {
        name: "Cagayan Provincial Road Network",
        client: "PowerNet Solutions",
        location: "Cagayan, Philippines",
        status: "active",
        description: "Construction and paving of 60km provincial road network",
        progress: 65,
        dueDate: "Jul 22, 2026",
        members: 23,
        sensors: 16,
        budget: 210_000_000,
        esgScore: 90,
        certifications: ["Cert #1", "Cert #2", "Cert #3", "Cert #4"],
        roiEstimate: 14.2,
        lastAuditDate: "Jul 18, 2025",
    },
    {
        name: "General Santos Fishing Port Upgrade",
        client: "SeaHarvest Infra",
        location: "General Santos, Philippines",
        status: "completed",
        description: "Expansion of fishing port with upgraded cold storage and piers",
        progress: 100,
        dueDate: "Jan 15, 2025",
        members: 26,
        sensors: 12,
        budget: 95_000_000,
        esgScore: 80,
        certifications: ["Cert #1", "Cert #2", "Cert #3", "Cert #4", "Cert #5"],
        roiEstimate: 8.7,
        lastAuditDate: "Feb 10, 2025",
    },
];

